name: azurefilesdemo
"on":
    push:
        branches:
            - main
    workflow_dispatch: {}

jobs:
    build:
        runs-on: arc-runner-set
        env:
          NUGET_PACKAGES: /home/runner/.nuget/packages
          DOTNET_INSTALL_DIR: "./.dotnet"
        steps:
            - uses: actions/checkout@v4
            - name: Install cURL Headers
              run: |
                sudo apt-get update
                sudo apt-get -y install curl
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '6.x'
            - name: Cache NuGet Packages
              id: nuget-packages
              uses: actions/cache@v4
              env:
                cache-name: nuget-package-cache
              with:
                path: /home/runner/.nuget/packages
                key: ${{ runner.os }}-${{ env.cache-name }}
            - name: List NuGet Packages
              if: ${{ steps.nuget-packages.outputs.cache-hit == 'true' }}
              continue-on-error: true
              run: ls -lh /home/runner/.nuget/packages                
            - name: Build dotnet app
              run: dotnet build dotnetdemo.csproj
