name: azurefilesdemo
"on":
    push:
        branches:
            - main
    workflow_dispatch: {}

jobs:
    build:
        runs-on: arc-runner-set
        env:
          DOTNET_INSTALL_DIR: "./.dotnet"        
        steps:
            - uses: actions/checkout@v4
            - name: Create nuget packages directory
              run: ls ~/.nuget/packages/
              shell: bash            
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '6.x'
            - name: Build dotnet app
              run: dotnet restore dotnetdemo.csproj
