name: azurefilesdemo
"on":
    push:
        branches:
            - main
    workflow_dispatch: {}

jobs:
    build:
        runs-on: arc-runner-set
        steps:
            - uses: actions/checkout@v4
            - name: Install cURL Headers
              run: |
                sudo apt-get update
                sudo apt-get -y install curl
            - uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '6.x'
            - name: Build dotnet app
              run: dotnet build dotnetdemo.csproj
